export interface Airport {
  code: string;
  city: string;
  country: string;
}

export const airports: Airport[] = [
  // South America
  { code: "GRU", city: "Sao Paulo Guarulhos", country: "BR" },
  { code: "GIG", city: "Rio de Janeiro", country: "BR" },
  { code: "BSB", city: "Brasilia", country: "BR" },
  { code: "CNF", city: "Belo Horizonte", country: "BR" },
  { code: "SSA", city: "Salvador", country: "BR" },
  { code: "REC", city: "Recife", country: "BR" },
  { code: "POA", city: "Porto Alegre", country: "BR" },
  { code: "CWB", city: "Curitiba", country: "BR" },
  { code: "FOR", city: "Fortaleza", country: "BR" },
  { code: "VCP", city: "Campinas", country: "BR" },
  { code: "FLN", city: "Florianopolis", country: "BR" },
  { code: "SDU", city: "Rio de Janeiro Santos Dumont", country: "BR" },
  { code: "CGH", city: "Sao Paulo Congonhas", country: "BR" },
  { code: "BEL", city: "Belem", country: "BR" },
  { code: "MAO", city: "Manaus", country: "BR" },
  { code: "NAT", city: "Natal", country: "BR" },
  { code: "MCZ", city: "Maceio", country: "BR" },
  { code: "VIX", city: "Vitoria", country: "BR" },
  { code: "CGB", city: "Cuiaba", country: "BR" },
  { code: "GYN", city: "Goiania", country: "BR" },
  { code: "EZE", city: "Buenos Aires Ezeiza", country: "AR" },
  { code: "AEP", city: "Buenos Aires Aeroparque", country: "AR" },
  { code: "COR", city: "Cordoba", country: "AR" },
  { code: "MDZ", city: "Mendoza", country: "AR" },
  { code: "BRC", city: "Bariloche", country: "AR" },
  { code: "IGR", city: "Iguazu", country: "AR" },
  { code: "SCL", city: "Santiago", country: "CL" },
  { code: "BOG", city: "Bogota", country: "CO" },
  { code: "MDE", city: "Medellin", country: "CO" },
  { code: "CTG", city: "Cartagena", country: "CO" },
  { code: "CLO", city: "Cali", country: "CO" },
  { code: "LIM", city: "Lima", country: "PE" },
  { code: "CUZ", city: "Cusco", country: "PE" },
  { code: "UIO", city: "Quito", country: "EC" },
  { code: "GYE", city: "Guayaquil", country: "EC" },
  { code: "MVD", city: "Montevideo", country: "UY" },
  { code: "ASU", city: "Asuncion", country: "PY" },
  { code: "VVI", city: "Santa Cruz", country: "BO" },
  { code: "LPB", city: "La Paz", country: "BO" },
  { code: "CCS", city: "Caracas", country: "VE" },
  { code: "PTY", city: "Panama City", country: "PA" },
  { code: "SJO", city: "San Jose", country: "CR" },

  // North America
  { code: "JFK", city: "New York JFK", country: "US" },
  { code: "LGA", city: "New York LaGuardia", country: "US" },
  { code: "EWR", city: "Newark", country: "US" },
  { code: "LAX", city: "Los Angeles", country: "US" },
  { code: "SFO", city: "San Francisco", country: "US" },
  { code: "ORD", city: "Chicago O'Hare", country: "US" },
  { code: "ATL", city: "Atlanta", country: "US" },
  { code: "DFW", city: "Dallas Fort Worth", country: "US" },
  { code: "DEN", city: "Denver", country: "US" },
  { code: "MIA", city: "Miami", country: "US" },
  { code: "FLL", city: "Fort Lauderdale", country: "US" },
  { code: "MCO", city: "Orlando", country: "US" },
  { code: "SEA", city: "Seattle", country: "US" },
  { code: "BOS", city: "Boston", country: "US" },
  { code: "IAD", city: "Washington Dulles", country: "US" },
  { code: "DCA", city: "Washington Reagan", country: "US" },
  { code: "PHL", city: "Philadelphia", country: "US" },
  { code: "IAH", city: "Houston", country: "US" },
  { code: "MSP", city: "Minneapolis", country: "US" },
  { code: "DTW", city: "Detroit", country: "US" },
  { code: "CLT", city: "Charlotte", country: "US" },
  { code: "PHX", city: "Phoenix", country: "US" },
  { code: "SAN", city: "San Diego", country: "US" },
  { code: "TPA", city: "Tampa", country: "US" },
  { code: "PDX", city: "Portland", country: "US" },
  { code: "SLC", city: "Salt Lake City", country: "US" },
  { code: "BNA", city: "Nashville", country: "US" },
  { code: "AUS", city: "Austin", country: "US" },
  { code: "RDU", city: "Raleigh Durham", country: "US" },
  { code: "STL", city: "St Louis", country: "US" },
  { code: "HNL", city: "Honolulu", country: "US" },
  { code: "SJU", city: "San Juan", country: "PR" },
  { code: "YYZ", city: "Toronto", country: "CA" },
  { code: "YVR", city: "Vancouver", country: "CA" },
  { code: "YUL", city: "Montreal", country: "CA" },
  { code: "YYC", city: "Calgary", country: "CA" },
  { code: "YOW", city: "Ottawa", country: "CA" },
  { code: "MEX", city: "Mexico City", country: "MX" },
  { code: "CUN", city: "Cancun", country: "MX" },
  { code: "GDL", city: "Guadalajara", country: "MX" },
  { code: "MTY", city: "Monterrey", country: "MX" },
  { code: "SJD", city: "San Jose del Cabo", country: "MX" },
  { code: "HAV", city: "Havana", country: "CU" },
  { code: "SDQ", city: "Santo Domingo", country: "DO" },
  { code: "PUJ", city: "Punta Cana", country: "DO" },
  { code: "KIN", city: "Kingston", country: "JM" },
  { code: "MBJ", city: "Montego Bay", country: "JM" },
  { code: "NAS", city: "Nassau", country: "BS" },

  // Europe
  { code: "LHR", city: "London Heathrow", country: "GB" },
  { code: "LGW", city: "London Gatwick", country: "GB" },
  { code: "STN", city: "London Stansted", country: "GB" },
  { code: "LTN", city: "London Luton", country: "GB" },
  { code: "MAN", city: "Manchester", country: "GB" },
  { code: "EDI", city: "Edinburgh", country: "GB" },
  { code: "CDG", city: "Paris Charles de Gaulle", country: "FR" },
  { code: "ORY", city: "Paris Orly", country: "FR" },
  { code: "NCE", city: "Nice", country: "FR" },
  { code: "LYS", city: "Lyon", country: "FR" },
  { code: "MRS", city: "Marseille", country: "FR" },
  { code: "FRA", city: "Frankfurt", country: "DE" },
  { code: "MUC", city: "Munich", country: "DE" },
  { code: "BER", city: "Berlin", country: "DE" },
  { code: "HAM", city: "Hamburg", country: "DE" },
  { code: "DUS", city: "Dusseldorf", country: "DE" },
  { code: "AMS", city: "Amsterdam", country: "NL" },
  { code: "MAD", city: "Madrid", country: "ES" },
  { code: "BCN", city: "Barcelona", country: "ES" },
  { code: "PMI", city: "Palma de Mallorca", country: "ES" },
  { code: "AGP", city: "Malaga", country: "ES" },
  { code: "FCO", city: "Rome Fiumicino", country: "IT" },
  { code: "MXP", city: "Milan Malpensa", country: "IT" },
  { code: "NAP", city: "Naples", country: "IT" },
  { code: "VCE", city: "Venice", country: "IT" },
  { code: "LIS", city: "Lisbon", country: "PT" },
  { code: "OPO", city: "Porto", country: "PT" },
  { code: "ZRH", city: "Zurich", country: "CH" },
  { code: "GVA", city: "Geneva", country: "CH" },
  { code: "VIE", city: "Vienna", country: "AT" },
  { code: "BRU", city: "Brussels", country: "BE" },
  { code: "DUB", city: "Dublin", country: "IE" },
  { code: "CPH", city: "Copenhagen", country: "DK" },
  { code: "OSL", city: "Oslo", country: "NO" },
  { code: "ARN", city: "Stockholm Arlanda", country: "SE" },
  { code: "HEL", city: "Helsinki", country: "FI" },
  { code: "WAW", city: "Warsaw", country: "PL" },
  { code: "KRK", city: "Krakow", country: "PL" },
  { code: "PRG", city: "Prague", country: "CZ" },
  { code: "BUD", city: "Budapest", country: "HU" },
  { code: "OTP", city: "Bucharest", country: "RO" },
  { code: "SOF", city: "Sofia", country: "BG" },
  { code: "ATH", city: "Athens", country: "GR" },
  { code: "SKG", city: "Thessaloniki", country: "GR" },
  { code: "IST", city: "Istanbul", country: "TR" },
  { code: "SAW", city: "Istanbul Sabiha", country: "TR" },
  { code: "AYT", city: "Antalya", country: "TR" },
  { code: "TLV", city: "Tel Aviv", country: "IL" },
  { code: "KEF", city: "Reykjavik", country: "IS" },

  // Asia
  { code: "NRT", city: "Tokyo Narita", country: "JP" },
  { code: "HND", city: "Tokyo Haneda", country: "JP" },
  { code: "KIX", city: "Osaka Kansai", country: "JP" },
  { code: "ICN", city: "Seoul Incheon", country: "KR" },
  { code: "PEK", city: "Beijing", country: "CN" },
  { code: "PVG", city: "Shanghai Pudong", country: "CN" },
  { code: "HKG", city: "Hong Kong", country: "HK" },
  { code: "TPE", city: "Taipei", country: "TW" },
  { code: "SIN", city: "Singapore", country: "SG" },
  { code: "BKK", city: "Bangkok Suvarnabhumi", country: "TH" },
  { code: "DMK", city: "Bangkok Don Mueang", country: "TH" },
  { code: "KUL", city: "Kuala Lumpur", country: "MY" },
  { code: "CGK", city: "Jakarta", country: "ID" },
  { code: "DPS", city: "Bali Denpasar", country: "ID" },
  { code: "MNL", city: "Manila", country: "PH" },
  { code: "CEB", city: "Cebu", country: "PH" },
  { code: "SGN", city: "Ho Chi Minh City", country: "VN" },
  { code: "HAN", city: "Hanoi", country: "VN" },
  { code: "DEL", city: "New Delhi", country: "IN" },
  { code: "BOM", city: "Mumbai", country: "IN" },
  { code: "BLR", city: "Bangalore", country: "IN" },
  { code: "MAA", city: "Chennai", country: "IN" },
  { code: "CCU", city: "Kolkata", country: "IN" },
  { code: "CMB", city: "Colombo", country: "LK" },
  { code: "KTM", city: "Kathmandu", country: "NP" },
  { code: "DAC", city: "Dhaka", country: "BD" },

  // Middle East
  { code: "DXB", city: "Dubai", country: "AE" },
  { code: "AUH", city: "Abu Dhabi", country: "AE" },
  { code: "DOH", city: "Doha", country: "QA" },
  { code: "RUH", city: "Riyadh", country: "SA" },
  { code: "JED", city: "Jeddah", country: "SA" },
  { code: "AMM", city: "Amman", country: "JO" },
  { code: "BAH", city: "Bahrain", country: "BH" },
  { code: "MCT", city: "Muscat", country: "OM" },
  { code: "KWI", city: "Kuwait City", country: "KW" },

  // Africa
  { code: "JNB", city: "Johannesburg", country: "ZA" },
  { code: "CPT", city: "Cape Town", country: "ZA" },
  { code: "CAI", city: "Cairo", country: "EG" },
  { code: "CMN", city: "Casablanca", country: "MA" },
  { code: "RAK", city: "Marrakech", country: "MA" },
  { code: "NBO", city: "Nairobi", country: "KE" },
  { code: "LOS", city: "Lagos", country: "NG" },
  { code: "ABJ", city: "Abidjan", country: "CI" },
  { code: "ADD", city: "Addis Ababa", country: "ET" },
  { code: "DSS", city: "Dakar", country: "SN" },
  { code: "TUN", city: "Tunis", country: "TN" },
  { code: "ALG", city: "Algiers", country: "DZ" },

  // Oceania
  { code: "SYD", city: "Sydney", country: "AU" },
  { code: "MEL", city: "Melbourne", country: "AU" },
  { code: "BNE", city: "Brisbane", country: "AU" },
  { code: "PER", city: "Perth", country: "AU" },
  { code: "AKL", city: "Auckland", country: "NZ" },
  { code: "WLG", city: "Wellington", country: "NZ" },
  { code: "CHC", city: "Christchurch", country: "NZ" },
  { code: "NAN", city: "Nadi", country: "FJ" },
  { code: "PPT", city: "Papeete", country: "PF" },
];

export function searchAirports(query: string): Airport[] {
  if (!query || query.length < 1) return [];
  const q = query.toLowerCase();
  return airports
    .filter(
      (a) =>
        a.code.toLowerCase().startsWith(q) ||
        a.city.toLowerCase().includes(q) ||
        a.country.toLowerCase() === q
    )
    .slice(0, 8);
}
